### ISSUE TITLE
Add client in terminology

### ISSUE THREAD

**Issue by nikosft** [ietf-wg-scitt/draft-ietf-scitt-architecture#102]
In section 5.2.3.3 `client` appears out of the blue. It is not clear what a `client` is.

**Comment by SteveLasker** [comment]
Hi, @nikosft 
I'm looking for the reference to 5.2.3.3 in https://www.ietf.org/archive/id/draft-ietf-scitt-architecture-02.html and other versions. 
I don't see where that section exists.
Are you referring to a reference where a client is calls the Transparency Service APIs?
Or, as there a mention of "client, synonymous with consumer, verifier, etc?

**Comment by nikosft** [comment]
E.g., 

> a Transparency Service MAY additionally support verifiability of client authentication and access control

Is the client the issuer itself? A piece of software that the issuer uses (e.g., a la OAuth2 client)? Does it refer to any role (issuer, verifier, auditor)? IMHO the text should be more specific, e.g., Certificate Transparency RFC explicitly mentions `TLS client`

**Comment by SteveLasker** [comment]
Thanks, @nikosft 
The above text is from Draft 04: [5.2.3.3. ](https://www.ietf.org/archive/id/draft-ietf-scitt-architecture-04.html#section-5.2.3.3)[Replayability and Auditing](https://www.ietf.org/archive/id/draft-ietf-scitt-architecture-04.html#name-replayability-and-auditing)

I've labeled it for terminology clarification.

**Comment by aj-stein-nist** [comment]
In that vein, I would support clarifying it with a "an Issue or Verifier's Transparency Service API client" in the applicable areas of the draft. Would that be more helpful or does it not reduce ambiguity?

**Comment by aj-stein-nist** [comment]
Just an update, I plan to send a PR with proposed changes this week.

**Comment by SteveLasker** [comment]
From the architecture/editors meeting
Differentiating:
- **Issuer** who signs the statement (The identity of the software component - Wabbit Networks)
- **Client** who initiates the registration operation, which encompasses RBAC which is not part of the spec, beyond being authenticated (the build system's identity for access control. The build system has a role to perform operations) - possibly refer to OAuth's definition of client
- **Verifier** who evaluates a statement. The verifier cares about the issuer, to know it was signed by a particular issuer. The audit of a supply chain will check the identities involved in the operations.

**Comment by mwiseman-byid** [comment]
AJ and I will review this

**Comment by aj-stein-nist** [comment]
@mwiseman-byid and I met today to discuss a recap of the authors/editorial meeting (sorry I missed) and how we need to think about 1) a better alternative name and 2) provide a rationale to why we need to have 1, name or not (part of that is the subject of this issue and pending work that should come up in #120 for the latter.

For 1, Monty and I are leaning towards agent for now, but we need to brainstorm on adjusted architecture to reflect 2 and "the way" and how it relates to requested edits for the relying party issue in #120.

We will post in progress work and continue to collaborate and sync, updating the WG via mailing list when it is ready for review and feedback across the WG. More to follow.

**Comment by SteveLasker** [comment]
Thanks, @aj-stein-nist, @mwiseman-byid for the focused discussion.

**Comment by aj-stein-nist** [comment]
OK, my work on #120 also led me to be confused and think maybe we have meant agent/client when we said verifier. I made some strawman diagrams to discuss this WG members in https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/120#issuecomment-1865318043.

/cc @mwiseman-byid

**Comment by aj-stein-nist** [comment]
OK, it seems we are converging in a direction on #120 around verifier and relying party. The diagram based on author feedback demonstrates that with #156 likely updates to the spec forthcoming if that is approved. It turns out, not surprisingly, we need both verifier and relying party. The latter, if tweak terminology, could more clearly refer to client and resolve this issue as well.

Given that, and how it relates to here, I would argue that relying party is the correct substitute for client and this could be closed as a duplicate or modified accordingly to address that.

This change would be in line with with the RATS specification *iff* we distinguish between Verifier Owner/Verifier (person entity/logical system for that entity) and Relying Party Owner/Relying Party (person entity/logical system for that entity) and ironically [current I-D version 2.x of the OAuth AuthZ Framework](https://datatracker.ietf.org/doc/draft-ietf-oauth-v2-1/https://datatracker.ietf.org/doc/draft-ietf-oauth-v2-1/), various OAuth WG drafts (even if it seems not formally defined), and [the OpenID Connect Specification](https://openid.net/specs/openid-connect-core-1_0.html#Terminology). 

It was unclear in previous discussion with authors if this is preferable or required, but it nicely aligns with small tactical changes to the diagram in #156 and relevant spec alignment in terminology and explanations.

**Comment by SteveLasker** [comment]
Still active. @aj-stein-nist, do you have time to complete this item?

**Comment by aj-stein-nist** [comment]
I had presented on this topic and we had agreed some key revisions had to take place before we could decide to make adjustments. Are we at that point?

Additionally, the alignment with RATS and other specs: is this necessary or not? There are some open questions that are not covered, re https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/102#issuecomment-1885309749. I guess I will take it to the list.
