### ISSUE TITLE
CT: Signed Certificate Timestamps are checked by Relying Parties

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-wg-scitt/draft-ietf-scitt-architecture#263]
> [Signed Certificate Timestamps are checked by Relying Parties](https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/blob/268-figure-1-description/draft-ietf-scitt-architecture.md?plain=1#L319)

I would argue that in CT Auditors are checking more than Signed Certificate Timestamps

**Comment by aj-stein-nist** [comment]
@hannestschofenig there is a lot of detail there and I am not sure how far you/others want to go, but I decided to keep it simple and I propose adding slightly more detail in https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/301. I am sure you and others will let me know if that is too little (I doubt/hope it is not too much.)

**Comment by SteveLasker** [comment]
@hannestschofenig, thanks for the issue. 
Did you have an intent for what to scope? Reading the [current content of this section](https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/blob/268-figure-1-description/draft-ietf-scitt-architecture.md?plain=1#L313), it implies a unique focus on x.509, rather than x.509 is one example of identity types that are supported.

> SCITT is a generalization of Certificate Transparency (CT) {{-CT}}, which can be interpreted as a transparency architecture for the supply chain of X.509 certificates.
Considering CT in terms of SCITT:
>
> - CAs (Issuers) sign the ASN.1 DER encoded tbsCertificate structure to produce an X.509 certificate (Signed Statements)
> - CAs submit the certificates to one or more CT logs (Transparency Services)
> - CT logs produce Signed Certificate Timestamps (Transparent Statements)
> - Signed Certificate Timestamps are checked by Relying Parties
> - The Append-only Log can be checked by Auditors

I'd suggest we limit the focus on x.509, and focus on the generalization that an issuer signs the protected header, which includes producing a timestamped signed statement and a timestamped receipt.
