### ISSUE TITLE
Ensure consistent use of "registered" to replace "recorded" when referring to signed statements being appended to the log. 

### ISSUE THREAD

**Issue by rjb4standards** [ietf-wg-scitt/draft-ietf-scitt-architecture#293]
We are inconsistent with our use of "registered" and "recorded" when referring to the addition of signed statements to the append-only log.

I recommend using the term "registered" consistently to refer to this act. This implies that some "process" was applied before registration can occur on the append-only log.

**Comment by JAG-UK** [comment]
Doing a quick search it seems easy and good to make this change, except one place that looks a bit janky.

The current document (draft-08 as released) includes a line:

Transparency Services MUST feature an Append-only Log. The Append-only Log is the verifiable data structure that records Signed Statements and supports the production of Receipts.

> It doesn't quite sound technically right to simply replace the word here because the VDS doesn't register things: there are other bits of the higher level TS involved there.

Would it satisfy you in this case to change to:

> Transparency Services MUST feature an Append-only Log. The Append-only Log is the verifiable data structure that records registered Signed Statements and supports the production of Receipts.

I don't want to mess too much with meaningful text changes and it would be a shame to hold up this issue for one detail. And I think this is strictly better because it also suggests that the VDS *doesn't* record (or validate, or witness, or any other word we might have come up with) Signed Statements that *haven't* been registered.

**Comment by rjb4standards** [comment]
No objections here Jon. Thanks for resolving this issue so quickly

**Comment by JAG-UK** [comment]
https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/296

**Comment by SteveLasker** [comment]
Closing as resolved by #296
